# Generated by Django 4.1.4 on 2022-12-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=250, unique_for_date="publish"),
        ),
    ]
